### ISSUE TITLE
[Suggestion] Skip system specific settings from sync

### ISSUE THREAD

**Issue by mubaidr** [nonoroazoro/vscode-syncing#20]
Some settings are very system specific or network dependent, for example, proxy settings. This could cause issue where you have one pc behind proxy server and other one is using direct Internet. 

Is there any possibility we can skip some settings from sync, these are kept as it is between sync. 

relevant setting: `http.proxy`

**Comment by nonoroazoro** [comment]
@mubaidr Mmm, I met this issue too... 😃 I think it's better to put this proxy settings into Syncing's own settings file.
I'll add this feature in the next release, soon.

**Comment by nonoroazoro** [comment]
@mubaidr The new version has been released (`Syncing v1.5.0`), brief changes:

- Rewrite in `TypeScript`, now we have `typings`.
- Pick `http_proxy` settings from `http_proxy` and `https_proxy` environment variables.
- Isolate the `http_proxy` setting into `Syncing`'s settings file (which means `Syncing` will no longer read proxy settings from `VSCode` settings), this may prevent a potential failure caused by wrong proxy settings while syncing between different devices.

Thanks again~ I hope you like it!

**Comment by mubaidr** [comment]
Awesome!

**Comment by mubaidr** [comment]
Well, this causes another issue. :/ Now manually installing extensions does not work because proxy configuration is missing from vs-code settings. Though vscode should be using `http_proxy` enviromental var but it does not seem so.

**Comment by nonoroazoro** [comment]
@mubaidr That's not caused by `Syncing`... You still can set `http_proxy` in VSCode 😄
