### ISSUE TITLE
Suspended on Xubuntu, Linux Mint while downloading extensions

### ISSUE THREAD

**Issue by sa3m** [nonoroazoro/vscode-syncing#21]
Hi, thanks for your plugins.
I'm experiencing troubles though while trying to download the gist config to another computer.

## Specifications

* OS Version: Xubuntu 16.04

* VSCode Version: 1.19

## Expected Behavior
Installing Gitlens

## Actual Behavior
Spinning forever

## Steps to Reproduce

1. Download a gist (https://gist.github.com/sa3m/8e9155dd464fd5852b4849e141f15f4e)

2. Watch installer spinning :)

I have another question about the default behavior:
I would like to spread my settings to my colleagues PCs.
I know that from my mac, it creates a gist with a settings-mac.json file.
Would it be possible to allow to copy that file to every to other distros when downloading if there is no specific settings.json in the gist ?

**Comment by nonoroazoro** [comment]
@sa3m I've tested your gist, and everything went well 😄. It seems that the issue is caused by a low-speed network connection. Meanwhile, you may notice that the release of `Git Lens` is way too large to download 😭, which is also part of the reason.

<img width="311" alt="default" src="https://user-images.githubusercontent.com/383132/34138939-07e5e2a0-e4ad-11e7-890a-ac4f8fe1b01d.png">

I suggest you check your internet connection or sync through a http proxy.

And for your last question: Of cause you can copy that file into another gist, but **remember to change its name to `settings.json`** if you're downloading **a Mac's setting** to a **Windows PC**. (You can simply make two copies, one is `settings.json`, the other is `settings-mac.json`).

**Comment by sa3m** [comment]
I tried on another PC and it went well... Don't know why it froze on the first one. We don't have any problem with internet here... Can I provide some more informations ?
About the sync, the idea was to synchronise all configs without having to manually copy the settings file which is a tedious solution (I update regularly the settings, so I'll have to copy it each time)...
Would it be possible to force agnostic settings (meaning no "-mac") ?
Thanks for your time.

**Comment by nonoroazoro** [comment]
@sa3m As far as I know, the endless spinning is because the downloading of `GitLens` is failed. Did you unintentionally set the `http_proxy` or `https_proxy` in the system environment ?, as `Syncing` will read proxy settings from environment variables.
_(About the informations, `Syncing` doesn't have any logging yet 😢, it only shows error messages in VSCode statusbar for now,  but I will try to add one in the next release, sorry!)_

---

For your second question, currently the settings of `Mac` and `non-Mac` are totally separated, including  `settings.json` and `keybindings.json` (as they're usually quite different). Unfortunately, there's no way to automatically sync the `Mac`'s settings to a `Windows/Linux... PC` for now.

But maybe it's a good idea to automatically download the `settings-mac.json` file while there's no `settings.json` in the Gist - and vice versa. I will consider adding this feature.

I'm very sorry for the inconvenience. Thank your for your feedback!

**Comment by silver-mx** [comment]
I am having the same issue but with other packages, I created this issue https://github.com/nonoroazoro/vscode-syncing/issues/22, but I assume it is a duplicate. I discard the bandwidth issue in my case. The internet works more than fine, and a windows machine can download the problematic packages without problem. Still linux mint has issues. I think it is a linux (ubuntu) problem maybe?

**Comment by nonoroazoro** [comment]
@silver-mx Thank you for the feedback. I'll test in a linux mint 17.3 machine and try to find out what's happened.

**Comment by nonoroazoro** [comment]
@silver-mx @sa3m I think I've determined the root cause.

In `Syncing`, I use [adm-zip](https://github.com/cthackers/adm-zip) to extract the downloaded extension zip files, which will throw exceptions on Linux Mint and Xubuntu (while it works on Windows and Mac... 😢).

I'll fix this issue in the next release.

**Comment by silver-mx** [comment]
@nonoroazoro nice you found the issue. Thanks for the great job with this extension, I have found it very useful! keep the good work!

**Comment by sa3m** [comment]
Thanks a lot !
