### ISSUE TITLE
Merge `settings.json`, `settings-mac.json` into one single file.

### ISSUE THREAD

**Issue by f8ttyc8t** [nonoroazoro/vscode-syncing#24]
## Specifications

* OS Version:
Machine 1 - Windows 10 Pro,
Machine 2 - MacOS 10.13.3
* VSCode Version:
1.20.2
## Expected Behavior
Configurations are synched between different machines.

## Actual Behavior
Synch only works when done at same Operating System.

## Steps to Reproduce

1. Upload config on Windows machine

2. Download config on Mac

3. Nothing changes at Mac side. 
But 2 settings files are created inside ghist: `settings.json` and `settings-mac.json`.

**Comment by nonoroazoro** [comment]
For `mac` and `windows`, the `settings` are separated, thus the mac's settings will not be synchronized to a windows machine and vice versa.

**Comment by agross** [comment]
> For mac and windows machines, the settings are separated

It would be great it that could be changed in the future.

I want to get rid of the competitor plugin because it's so damn buggy. It keeps key bindings in separate Gist files, but uses the same file for `settings.json`. That part (syncing settings) generally works quite well. I wonder, what are the reasons to keep the settings (not key bindings!) separate by platform? And also, why is only macOS handled specially, but not Linux?

**Comment by nonoroazoro** [comment]
@agross Usually the `font` settings (such as `editor.fontSize` and `editor.fontFamily`) and the `http.proxy` are quite different between Windows and Mac (I guess I forget the Linux...), and that's why I decided to separate the files.

But I still agree with your opion. In fact, I'm already considering to merge these `settings` into one singe file, and recently I've added a new feature so we can exclude some VSCode settings from being synced, which I think may reduce the impact of migrating to one sigle `settings.json` file.

**Comment by agross** [comment]
@nonoroazoro Thank you for considering! 👍

**Comment by RobinD42** [comment]
I too would like to have the settings file not be split out for Mac. Perhaps you could make it an optional setting if there are good reasons to keep them split? That way those of use who would rather not split would be able to do so.

**Comment by nonoroazoro** [comment]
@f8ttyc8t @agross @RobinD42 , I've released the new version ([latest release](https://github.com/nonoroazoro/vscode-syncing/releases/tag/v1.7.2)) for this feature, enjoy!

**Comment by f8ttyc8t** [comment]
Thank you very much for updating it!
