### ISSUE TITLE
How do I make the settings be sync'd automatically?

### ISSUE THREAD

**Issue by brandoncc** [nonoroazoro/vscode-syncing#6]
I would like the settings to sync automatically when I open and close VS Code. How do I do that?

**Comment by nonoroazoro** [comment]
@brandoncc No, you can't. I'm sorry that there's no `automatic synchronization` here.

The reason is: when you're trying out some new extensions or settings, It will falsely overwrite the current settings and this is nothing but a nightmare.`

Comparing to its benefits, I choose to keep everything under your control. Sorry for the inconvenience.

**Comment by brandoncc** [comment]
What about providing an option? That is what https://github.com/golf1052/code-sync does. Unfortunately that extension seems to be very buggy so I can't use it, which is how I found your extension. They offer an option for "auto download" separate from "auto upload". This would ease your concerns and still make those who want the option happy. Plus, there are revisions on gists so we could always just go backward manually if necessary.

**Comment by nonoroazoro** [comment]
@brandoncc Your're right, the auto-synchronization is very useful for some people.

In the very beginning, when I decided to make a new sync extension of VSCode, there's already a settings sync extension - [Settings Sync](https://marketplace.visualstudio.com/items?itemName=Shan.code-settings-sync) which is the most downloaded extension (You can try it 😸 ). But it's too complex for me and lacks some functionality (such as Proxy support) at that time.

That's why I want to keep `Syncing` as simple as possible and offer minimal but valuable features.

However, there may be an appropriate approach to add this auto-synchronization option without adding much complexity, but before that I can't promise anything.

**Comment by brandoncc** [comment]
Thank you for telling me about that. I respect your wish to keep your extension as simple as possible. The extension you told me about handles what I wanted, so I will use that. Thank you again!

**Comment by nonoroazoro** [comment]
Auto-sync is added as so many people want it...
